version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payroll-system-app
    restart: unless-stopped
    working_dir: /var/www/payroll-system
    volumes:
      - ./:/var/www/payroll-system
      - ./storage:/var/www/payroll-system/storage
      - ./bootstrap/cache:/var/www/payroll-system/bootstrap/cache
    networks:
      - payroll-network
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://your-domain.com
      - APP_TIMEZONE=Asia/Jakarta
      - APP_LOCALE=id
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=payroll_system
      - DB_USERNAME=payroll_user
      - DB_PASSWORD=strong_password_here
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-app-password
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=noreply@your-domain.com
      - MAIL_FROM_NAME=Payroll Management System
      - FILESYSTEM_DISK=local
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=error
      - BROADCAST_DRIVER=log
      - SESSION_SECURE_COOKIE=true
      - SESSION_SAME_SITE=lax
      - SANCTUM_STATEFUL_DOMAINS=your-domain.com
      - API_RATE_LIMIT=60
      - API_RATE_LIMIT_WINDOW=60
      - TAX_PTKP_RATES='{"TK/0": 54000000,"TK/1": 58500000,"TK/2": 63000000,"TK/3": 67500000,"K/0": 58500000,"K/1": 63000000,"K/2": 67500000,"K/3": 72000000}'
      - TAX_BRACKETS='[{"min": 0,"max": 60000000,"rate": 5},{"min": 60000000,"max": 250000000,"rate": 15},{"min": 250000000,"max": 500000000,"rate": 25},{"min": 500000000,"max": null,"rate": 30}]'
      - BPJS_KESEHATAN_EMPLOYEE_RATE=1.0
      - BPJS_KESEHATAN_EMPLOYER_RATE=4.0
      - BPJS_KETENAGAKERJAAN_JHT_EMPLOYEE_RATE=2.0
      - BPJS_KETENAGAKERJAAN_JHT_EMPLOYER_RATE=3.7
      - BPJS_KETENAGAKERJAAN_JKK_RATE=0.24
      - BPJS_KETENAGAKERJAAN_JKM_RATE=0.3
      - BPJS_KETENAGAKERJAAN_JP_EMPLOYEE_RATE=1.0
      - BPJS_KETENAGAKERJAAN_JP_EMPLOYER_RATE=2.0
      - OVERTIME_REGULAR_RATE=1.5
      - OVERTIME_HOLIDAY_RATE=2.0
      - OVERTIME_NIGHT_SHIFT_RATE=1.3
      - LEAVE_ANNUAL_DAYS=12
      - LEAVE_SICK_DAYS=12
      - LEAVE_PERSONAL_DAYS=6
      - LEAVE_MATERNITY_DAYS=90
      - LEAVE_PATERNITY_DAYS=2
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=jpg,jpeg,png,pdf,doc,docx,xls,xlsx
      - BACKUP_ENABLED=true
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_TIME=02:00
      - MONITORING_ENABLED=true
      - HEALTH_CHECK_ENABLED=true
      - PERFORMANCE_MONITORING=true
      - HRIS_API_URL=https://hris.example.com/api
      - ACCOUNTING_API_URL=https://accounting.example.com/api
      - BANK_API_URL=https://bank.example.com/api
      - BPJS_API_URL=https://bpjs.example.com/api
      - TAX_OFFICE_API_URL=https://pajak.go.id/api
      - FORCE_HTTPS=true
      - SECURE_HEADERS=true
      - OPCACHE_ENABLED=true
      - OPCACHE_MEMORY_CONSUMPTION=128
      - OPCACHE_MAX_ACCELERATED_FILES=4000
      - DB_STRICT=false
      - DB_ENGINE=InnoDB
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - SESSION_ENCRYPT=true
      - SESSION_SECURE=true
      - SESSION_HTTP_ONLY=true
      - COOKIE_SECURE=true
      - COOKIE_HTTP_ONLY=true
      - COOKIE_SAME_SITE=lax
      - SECURITY_HEADERS=true
      - X_FRAME_OPTIONS=SAMEORIGIN
      - X_CONTENT_TYPE_OPTIONS=nosniff
      - X_XSS_PROTECTION="1; mode=block"
      - REFERRER_POLICY=strict-origin-when-cross-origin
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_ATTEMPTS=60
      - RATE_LIMIT_MINUTES=1
      - API_VERSION=v1
      - API_PREFIX=api
      - API_DEBUG=false
      - MOBILE_API_ENABLED=true
      - MOBILE_API_VERSION=v1
      - MOBILE_PUSH_NOTIFICATIONS=true
      - WEBHOOK_ENABLED=true
      - WEBHOOK_SECRET=your-webhook-secret-here
      - WEBHOOK_TIMEOUT=30
      - AUDIT_ENABLED=true
      - AUDIT_RETENTION_DAYS=2555
      - AUDIT_LOG_LEVEL=info
      - ARCHIVE_ENABLED=true
      - ARCHIVE_RETENTION_DAYS=1825
      - ARCHIVE_AUTO_CLEANUP=true
      - EMAIL_TEMPLATES_PATH=resources/views/emails
      - EMAIL_DEFAULT_TEMPLATE=default
      - NOTIFICATION_CHANNELS=mail,database
      - PUSH_NOTIFICATIONS_ENABLED=true
      - SMS_NOTIFICATIONS_ENABLED=false
      - REPORT_CACHE_ENABLED=true
      - REPORT_CACHE_TTL=3600
      - REPORT_EXPORT_FORMATS=pdf,excel,csv
      - INTEGRATION_WEBHOOK_URL=https://your-domain.com/api/webhooks
      - INTEGRATION_API_KEY=your-integration-api-key
      - INTEGRATION_TIMEOUT=30
      - DEBUGBAR_ENABLED=false
      - TELESCOPE_ENABLED=false
      - HORIZON_ENABLED=true
      - MAINTENANCE_MODE=false
      - MAINTENANCE_SECRET=your-maintenance-secret
      - COMPANY_NAME=Your Company Name
      - COMPANY_ADDRESS=Your Company Address
      - COMPANY_PHONE=+62-21-1234567
      - COMPANY_EMAIL=info@your-domain.com
      - COMPANY_WEBSITE=https://your-domain.com
      - FEATURE_MOBILE_APP=true
      - FEATURE_API_INTEGRATION=true
      - FEATURE_ADVANCED_REPORTING=true
      - FEATURE_AUTOMATED_BACKUP=true
      - FEATURE_PERFORMANCE_MONITORING=true
      - GOOGLE_ANALYTICS_ID=GA-XXXXXXXXX-X
      - FACEBOOK_PIXEL_ID=XXXXXXXXXX
      - GOOGLE_TAG_MANAGER_ID=GTM-XXXXXXX
      - PAYMENT_GATEWAY=midtrans
      - MIDTRANS_SERVER_KEY=your-midtrans-server-key
      - MIDTRANS_CLIENT_KEY=your-midtrans-client-key
      - MIDTRANS_MERCHANT_ID=your-midtrans-merchant-id
      - SMS_GATEWAY=twilio
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - TWILIO_PHONE_NUMBER=+1234567890
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FACEBOOK_CLIENT_ID=your-facebook-client-id
      - FACEBOOK_CLIENT_SECRET=your-facebook-client-secret
      - CDN_ENABLED=true
      - CDN_URL=https://cdn.your-domain.com
      - CDN_ASSETS_PATH=/assets
      - CACHE_TTL=3600
      - CACHE_PREFIX=payroll_
      - CACHE_STORE=redis
      - QUEUE_WORKERS=2
      - QUEUE_TIMEOUT=60
      - QUEUE_RETRY_AFTER=90
      - QUEUE_MAX_TRIES=3
      - CRON_ENABLED=true
      - CRON_SCHEDULE="* * * * *"
      - CRON_LOG_ENABLED=true
      - ERROR_REPORTING_ENABLED=true
      - ERROR_REPORTING_EMAIL=errors@your-domain.com
      - ERROR_REPORTING_SLACK_WEBHOOK=https://hooks.slack.com/services/xxx/yyy/zzz
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_LICENSE_KEY=your-new-relic-license-key
      - NEW_RELIC_APP_NAME=Payroll System
      - LOGSTASH_ENABLED=false
      - LOGSTASH_HOST=logstash.your-domain.com
      - LOGSTASH_PORT=5000
      - DB_READ_HOST=mysql
      - DB_READ_PORT=3306
      - DB_READ_DATABASE=payroll_system
      - DB_READ_USERNAME=payroll_read_user
      - DB_READ_PASSWORD=strong_read_password
      - LOAD_BALANCER_ENABLED=false
      - LOAD_BALANCER_STICKY_SESSIONS=true
      - LOAD_BALANCER_HEALTH_CHECK_PATH=/health
      - SSL_CERTIFICATE_PATH=/etc/ssl/certs/your-domain.crt
      - SSL_PRIVATE_KEY_PATH=/etc/ssl/private/your-domain.key
      - SSL_CHAIN_PATH=/etc/ssl/certs/your-domain-chain.crt
      - FIREWALL_ENABLED=true
      - FIREWALL_ALLOWED_IPS=192.168.1.0/24,10.0.0.0/8
      - FIREWALL_BLOCKED_IPS=
      - BACKUP_STORAGE_DRIVER=local
      - BACKUP_STORAGE_PATH=/var/backups/payroll-system
      - MONITORING_ALERT_EMAIL=alerts@your-domain.com
      - MONITORING_ALERT_SLACK_CHANNEL=#payroll-alerts
      - MONITORING_DISK_THRESHOLD=80
      - MONITORING_MEMORY_THRESHOLD=85
      - MONITORING_CPU_THRESHOLD=90
      - API_DOCS_ENABLED=true
      - API_DOCS_PATH=/api/docs
      - API_DOCS_TITLE=Payroll System API Documentation
      - TESTING_ENABLED=false
      - TESTING_DATABASE=payroll_system_test
      - TESTING_MAIL_DRIVER=log
      - TESTING_QUEUE_DRIVER=sync
      - DEFAULT_LOCALE=id
      - FALLBACK_LOCALE=en
      - AVAILABLE_LOCALES=id,en
      - DEFAULT_TIMEZONE=Asia/Jakarta
      - SUPPORTED_TIMEZONES=Asia/Jakarta,Asia/Makassar,Asia/Jayapura
      - DEFAULT_CURRENCY=IDR
      - CURRENCY_SYMBOL=Rp
      - CURRENCY_DECIMALS=0
      - NUMBER_DECIMALS=2
      - NUMBER_THOUSANDS_SEPARATOR=.
      - NUMBER_DECIMAL_SEPARATOR=,
      - DATE_FORMAT=d/m/Y
      - TIME_FORMAT=H:i:s
      - DATETIME_FORMAT=d/m/Y H:i:s
      - UPLOAD_MAX_FILESIZE=64M
      - POST_MAX_SIZE=64M
      - MAX_FILE_UPLOADS=20
      - IMAGE_QUALITY=85
      - IMAGE_MAX_WIDTH=1920
      - IMAGE_MAX_HEIGHT=1080
      - IMAGE_THUMBNAIL_SIZE=150
      - PDF_DRIVER=dompdf
      - PDF_TEMP_PATH=/tmp
      - PDF_CACHE_ENABLED=true
      - EXCEL_DRIVER=phpspreadsheet
      - EXCEL_TEMP_PATH=/tmp
      - EXCEL_CACHE_ENABLED=true
      - EMAIL_TEMPLATE_ENGINE=blade
      - EMAIL_TEMPLATE_CACHE=true
      - EMAIL_TEMPLATE_PATH=resources/views/emails
      - NOTIFICATION_TEMPLATE_ENGINE=blade
      - NOTIFICATION_TEMPLATE_CACHE=true
      - NOTIFICATION_TEMPLATE_PATH=resources/views/notifications
      - REPORT_TEMPLATE_ENGINE=blade
      - REPORT_TEMPLATE_CACHE=true
      - REPORT_TEMPLATE_PATH=resources/views/reports
      - DASHBOARD_REFRESH_INTERVAL=300
      - DASHBOARD_CACHE_ENABLED=true
      - DASHBOARD_CACHE_TTL=300
      - SEARCH_DRIVER=database
      - SEARCH_INDEX_PATH=/var/search
      - SEARCH_CACHE_ENABLED=true
      - EXPORT_BATCH_SIZE=1000
      - EXPORT_TIMEOUT=300
      - EXPORT_TEMP_PATH=/tmp/exports
      - IMPORT_BATCH_SIZE=100
      - IMPORT_TIMEOUT=300
      - IMPORT_TEMP_PATH=/tmp/imports
      - IMPORT_VALIDATION_STRICT=true
      - VALIDATION_STRICT_MODE=true
      - VALIDATION_CUSTOM_RULES_ENABLED=true
      - VALIDATION_CACHE_ENABLED=true
      - FORM_CSRF_ENABLED=true
      - FORM_CSRF_TIMEOUT=120
      - FORM_CSRF_EXCLUDE_PATHS=api/*
      - SECURITY_PASSWORD_MIN_LENGTH=8
      - SECURITY_PASSWORD_REQUIRE_UPPERCASE=true
      - SECURITY_PASSWORD_REQUIRE_LOWERCASE=true
      - SECURITY_PASSWORD_REQUIRE_NUMBERS=true
      - SECURITY_PASSWORD_REQUIRE_SYMBOLS=true
      - SECURITY_PASSWORD_EXPIRY_DAYS=90
      - SECURITY_SESSION_TIMEOUT=120
      - SECURITY_MAX_LOGIN_ATTEMPTS=5
      - SECURITY_LOCKOUT_DURATION=15
      - TWO_FACTOR_ENABLED=true
      - TWO_FACTOR_DRIVER=google2fa
      - TWO_FACTOR_ISSUER=Payroll System
      - API_RATE_LIMIT_GUEST=30
      - API_RATE_LIMIT_AUTHENTICATED=60
      - API_RATE_LIMIT_ADMIN=120
      - WEBHOOK_MAX_RETRIES=3
      - WEBHOOK_RETRY_DELAY=60
      - WEBHOOK_TIMEOUT=30
      - WEBHOOK_SIGNATURE_HEADER=X-Webhook-Signature
      - AUDIT_LOG_ENABLED=true
      - AUDIT_LOG_LEVEL=info
      - AUDIT_LOG_RETENTION_DAYS=2555
      - AUDIT_LOG_SENSITIVE_FIELDS=password,credit_card,ssn
      - PRIVACY_GDPR_COMPLIANT=true
      - PRIVACY_DATA_RETENTION_DAYS=2555
      - PRIVACY_DATA_ANONYMIZATION=true
      - PRIVACY_COOKIE_CONSENT=true
      - COMPLIANCE_SOX_ENABLED=true
      - COMPLIANCE_ISO27001_ENABLED=true
      - COMPLIANCE_PCI_DSS_ENABLED=false
      - DISASTER_RECOVERY_ENABLED=true
      - DISASTER_RECOVERY_RPO=24
      - DISASTER_RECOVERY_RTO=4
      - DISASTER_RECOVERY_BACKUP_LOCATION=offsite
      - PERFORMANCE_QUERY_CACHE=true
      - PERFORMANCE_VIEW_CACHE=true
      - PERFORMANCE_CONFIG_CACHE=true
      - PERFORMANCE_ROUTE_CACHE=true
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=300
      - MAX_INPUT_TIME=300
      - DB_CONNECTION_POOL_SIZE=10
      - DB_CONNECTION_TIMEOUT=60
      - DB_CONNECTION_RETRY_ATTEMPTS=3
      - REDIS_CONNECTION_POOL_SIZE=10
      - REDIS_CONNECTION_TIMEOUT=60
      - REDIS_CONNECTION_RETRY_ATTEMPTS=3
      - QUEUE_WORKER_MEMORY_LIMIT=512M
      - QUEUE_WORKER_TIMEOUT=300
      - QUEUE_WORKER_SLEEP=3
      - QUEUE_WORKER_MAX_TRIES=3
      - CRON_JOB_MEMORY_LIMIT=256M
      - CRON_JOB_TIMEOUT=300
      - CRON_JOB_LOG_ENABLED=true
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_CHECK_INTERVAL=300
      - HEALTH_CHECK_TIMEOUT=30
      - HEALTH_CHECK_EMAIL_ALERTS=true
      - MONITORING_ENABLED=true
      - MONITORING_INTERVAL=60
      - MONITORING_METRICS_ENABLED=true
      - MONITORING_ALERTS_ENABLED=true
      - LOG_LEVEL=error
      - LOG_MAX_FILES=30
      - LOG_MAX_SIZE=10485760
      - LOG_CHANNELS=stack,daily,slack
      - ERROR_REPORTING_ENABLED=true
      - ERROR_REPORTING_EMAIL=errors@your-domain.com
      - ERROR_REPORTING_SLACK_WEBHOOK=https://hooks.slack.com/services/xxx/yyy/zzz
      - ERROR_REPORTING_SENTRY_DSN=https://your-sentry-dsn
      - DEBUGBAR_ENABLED=false
      - TELESCOPE_ENABLED=false
      - HORIZON_ENABLED=true
      - LOGVIEWER_ENABLED=false
      - MAINTENANCE_MODE=false
      - MAINTENANCE_SECRET=your-maintenance-secret
      - MAINTENANCE_ALLOWED_IPS=192.168.1.100,10.0.0.50
      - CUSTOM_FEATURE_FLAG_1=true
      - CUSTOM_FEATURE_FLAG_2=false
      - CUSTOM_API_ENDPOINT=https://custom-api.example.com
      - CUSTOM_INTEGRATION_KEY=your-custom-integration-key

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: payroll-system-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - ./storage:/var/www/payroll-system/storage
    networks:
      - payroll-network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: payroll-system-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: payroll_system
      MYSQL_USER: payroll_user
      MYSQL_PASSWORD: strong_password_here
      MYSQL_ROOT_PASSWORD: root_password_here
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - payroll-network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: payroll-system-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - payroll-network
    command: redis-server --appendonly yes

  # Supervisor for Queue Management
  supervisor:
    build:
      context: .
      dockerfile: Dockerfile.supervisor
    container_name: payroll-system-supervisor
    restart: unless-stopped
    volumes:
      - ./supervisor.conf:/etc/supervisor/conf.d/payroll-system.conf:ro
      - ./storage:/var/www/payroll-system/storage
    networks:
      - payroll-network
    depends_on:
      - app
      - mysql
      - redis

  # Monitoring (Optional)
  monitoring:
    image: prom/prometheus:latest
    container_name: payroll-system-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - payroll-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana Dashboard (Optional)
  grafana:
    image: grafana/grafana:latest
    container_name: payroll-system-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin_password_here
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - payroll-network

  # Backup Service
  backup:
    image: alpine:latest
    container_name: payroll-system-backup
    restart: unless-stopped
    volumes:
      - ./backup:/backup
      - mysql_data:/var/lib/mysql:ro
      - ./storage:/var/www/payroll-system/storage:ro
    networks:
      - payroll-network
    command: |
      sh -c "
        while true; do
          echo 'Starting backup...'
          mysqldump -h mysql -u payroll_user -pstrong_password_here payroll_system > /backup/db-backup-$(date +%Y%m%d-%H%M%S).sql
          tar -czf /backup/app-backup-$(date +%Y%m%d-%H%M%S).tar.gz -C /var/www payroll-system
          find /backup -name '*.sql' -mtime +7 -delete
          find /backup -name '*.tar.gz' -mtime +7 -delete
          echo 'Backup completed'
          sleep 86400
        done
      "

  # Health Check Service
  healthcheck:
    image: alpine:latest
    container_name: payroll-system-healthcheck
    restart: unless-stopped
    networks:
      - payroll-network
    command: |
      sh -c "
        while true; do
          if curl -f http://app/health > /dev/null 2>&1; then
            echo 'Health check passed'
          else
            echo 'Health check failed'
          fi
          sleep 30
        done
      "

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  payroll-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 